"""Phase 5: figures. All regenerated by `make figures` from data in the repo."""
import json
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, ".")

plt.rcParams.update({
    "figure.dpi": 150, "savefig.dpi": 150,
    "font.size": 9, "axes.titlesize": 10, "axes.labelsize": 9,
    "legend.fontsize": 8, "axes.grid": True, "grid.alpha": 0.3,
    "axes.spines.top": False, "axes.spines.right": False,
})

COND_LABELS = {
    "cond_A": "A: low effort, K=1",
    "cond_B": "B: high effort, K=1",
    "cond_C": "C: max effort, K=1",
    "cond_D": "D: high effort, K=10 (median)",
    "cond_E": "E: high effort, K=5, base-rate (median)",
    "baseline_base_rate": "Baseline: set base rate",
    "baseline_constant_half": "Baseline: constant 0.5",
    "baseline_crowd": "Baseline: Manifold crowd at close",
}


def load_pq():
    df = pd.DataFrame([json.loads(l) for l in open("data/parsed/parsed.jsonl")])
    qmeta = pd.DataFrame([json.loads(l) for l in open("data/questions.jsonl")]).set_index("qid")
    rows = []
    for (qid, cond), grp in df[df.parse_status == "ok"].groupby(["qid", "condition"]):
        probs = grp.sort_values("sample_idx").probability.values
        outcome = int(qmeta.loc[qid, "outcome"])
        rows.append({
            "qid": qid, "condition": cond, "outcome": outcome,
            "stratum": qmeta.loc[qid, "stratum"], "crowd": float(qmeta.loc[qid, "baseline_crowd_prob"]),
            "p": float(np.median(probs)) if len(probs) > 1 else float(probs[0]),
            "p_mean": float(np.mean(probs)),
        })
    return pd.DataFrame(rows)


def calibration_curve(p, y, n_bins=10):
    edges = np.linspace(0, 1, n_bins + 1)
    idx = np.clip(np.digitize(p, edges[1:-1], right=False), 0, n_bins - 1)
    xs, ys, ns = [], [], []
    for b in range(n_bins):
        m = idx == b
        if m.sum() == 0:
            xs.append((edges[b] + edges[b + 1]) / 2)
            ys.append(np.nan)
            ns.append(0)
        else:
            xs.append(p[m].mean())
            ys.append(y[m].mean())
            ns.append(int(m.sum()))
    return np.array(xs), np.array(ys), np.array(ns), edges


def fig_calibration_curves(pq):
    fig, (ax, axh) = plt.subplots(
        2, 1, figsize=(6.4, 6.0), sharex=True,
        gridspec_kw={"height_ratios": [3, 1], "hspace": 0.05})
    conds = ["A", "B", "C", "D", "E"]
    colors = plt.cm.viridis(np.linspace(0, 0.9, len(conds)))
    for cond, c in zip(conds, colors):
        s = pq[pq.condition == cond]
        p, y = s.p.values, s.outcome.values
        xs, ys, ns, edges = calibration_curve(p, y)
        ax.plot(xs, ys, "o-", color=c, label=f"{cond} (n={len(s)})", ms=4, lw=1.2)
        axh.bar((edges[:-1] + edges[1:]) / 2, ns, width=0.09, color=c, alpha=0.5)
    ax.plot([0, 1], [0, 1], "k--", lw=1, label="perfect")
    ax.set_ylabel("observed YES frequency")
    ax.set_title("Calibration by condition (pooled strata)")
    ax.legend(loc="upper left", framealpha=0.9)
    ax.set_xlim(0, 1); ax.set_ylim(0, 1)
    axh.set_xlabel("predicted probability (bin midpoint)")
    axh.set_ylabel("count of questions")
    fig.savefig("figures/calibration_curves.png", bbox_inches="tight")
    plt.close(fig)


def fig_brier_by_condition(pq):
    m = pd.read_csv("results/metrics.csv")
    m = m[(m.subset == "full") & m.label.str.startswith(("cond_", "baseline_"))]
    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    labels = [COND_LABELS.get(l, l) for l in m.label]
    vals = m.brier.values
    order = np.argsort(vals)
    colors = ["#4c72b0" if not l.startswith("Baseline") else "#cccccc"
              for l in m.label.values[order]]
    ax.barh(range(len(m)), vals[order], color=colors)
    ax.set_yticks(range(len(m)))
    ax.set_yticklabels([labels[i] for i in order], fontsize=8)
    for i, v in enumerate(vals[order]):
        ax.text(v + 0.002, i, f"{v:.3f}", va="center", fontsize=7)
    ax.set_xlabel("Brier score (lower is better)")
    ax.set_title("Brier score by condition and baseline")
    fig.savefig("figures/brier_by_condition.png", bbox_inches="tight")
    plt.close(fig)


def fig_brier_vs_k():
    c = pd.read_csv("results/k_curve.csv")
    fig, ax = plt.subplots(figsize=(5.6, 3.6))
    ax.plot(c.n, c.brier, "o-", color="#4c72b0")
    for _, row in c.iterrows():
        ax.annotate(f"{row.brier:.3f}", (row.n, row.brier),
                    textcoords="offset points", xytext=(0, 6), fontsize=7, ha="center")
    ax.set_xlabel("K samples aggregated (median)")
    ax.set_ylabel("Brier score")
    ax.set_title("Diminishing returns: Brier vs K (condition D, n questions fixed)")
    ax.set_xticks(c.n)
    fig.savefig("figures/brier_by_condition.png".replace("brier_by_condition", "brier_vs_k"),
                bbox_inches="tight")
    plt.close(fig)


def fig_rel_vs_res():
    m = pd.read_csv("results/metrics.csv")
    m = m[(m.subset == "full") & m.label.str.startswith("cond_")]
    fig, ax = plt.subplots(figsize=(5.0, 4.0))
    ax.scatter(m.resolution, m.reliability, s=40)
    for _, r in m.iterrows():
        ax.annotate(r.label.replace("cond_", ""), (r.resolution, r.reliability),
                    textcoords="offset points", xytext=(5, 5), fontsize=8)
    ax.set_xlabel("resolution (higher = more discrimination)")
    ax.set_ylabel("reliability (lower = better calibrated)")
    ax.set_title("Effort buys discrimination or calibration?")
    fig.savefig("figures/rel_vs_res.png", bbox_inches="tight")
    plt.close(fig)


def fig_contamination_split(pq):
    m = pd.read_csv("results/metrics.csv")
    m = m[m.label.str.startswith("cond_")]
    conds = ["A", "B", "C", "D", "E"]
    fig, ax = plt.subplots(figsize=(6.4, 3.8))
    width = 0.35
    x = np.arange(len(conds))
    for i, (subset, color, sign) in enumerate([("pre_cutoff", "#8172b2", -width / 2),
                                               ("post_cutoff", "#ccb974", +width / 2)]):
        vals = [m[(m.label == f"cond_{c}") & (m.subset == subset)].brier.values
                for c in conds]
        vals = [v[0] if len(v) else np.nan for v in vals]
        ax.bar(x + sign, vals, width, label=subset.replace("_", " "), color=color)
    ax.set_xticks(x)
    ax.set_xticklabels(conds)
    ax.set_xlabel("condition")
    ax.set_ylabel("Brier score")
    ax.set_title("Contamination split: pre vs post assumed cutoff (2026-08-15)")
    ax.legend()
    fig.savefig("figures/contamination_split.png", bbox_inches="tight")
    plt.close(fig)


def main():
    pq = load_pq()
    fig_calibration_curves(pq)
    fig_brier_by_condition(pq)
    fig_brier_vs_k()
    fig_rel_vs_res()
    fig_contamination_split(pq)
    print("figures written: calibration_curves.png, brier_by_condition.png, "
          "brier_vs_k.png, rel_vs_res.png, contamination_split.png")


if __name__ == "__main__":
    main()
